# Generated by Django 3.2.19 on 2023-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
